### ISSUE TITLE
App Hangs doesn't finish pulling information

### ISSUE THREAD

**Issue by menopreciado** [hawaiianchimp/kbb-craigslist#23]
Please fix:  the app hangs at "getting price" and never returns results.

thank you!!

**Comment by hawaiianchimp** [comment]
Hmm KBB must have changed their API again. I'll take a look.

**Comment by hawaiianchimp** [comment]
Temporary fix has been submitted to the Chrome Store. Still have to find a way to get original interface to work.
![screen shot 2015-03-03 at 1 01 50 pm](https://cloud.githubusercontent.com/assets/965298/6472204/83703354-c1a5-11e4-8e48-224ca8c42156.PNG)

**Comment by menopreciado** [comment]
thanks for the update

**Comment by hawaiianchimp** [comment]
It's fixed!
