### ISSUE TITLE
Mercedes-Benz not reading.

### ISSUE THREAD

**Issue by drgonzalez94** [hawaiianchimp/kbb-craigslist#25]
Most sellers on craigslist will not properly hyphenate Mercedes-Benz, and instead will list it as "Mercedes Benz". Selecting the right options in the drop down menu causes an error and will force open the KBB site instead of continuing.

**Comment by hawaiianchimp** [comment]
Thanks @drgonzalez94, I'll take a look at this. Do you have a link to an example listing?

**Comment by hawaiianchimp** [comment]
I just submitted a patch that should solve the error box from showing. Tested it on this page: http://losangeles.craigslist.org/sgv/cto/4970455599.html

This patch does not fix the hyphen yet

**Comment by drgonzalez94** [comment]
Great to see such quick support. Installed. Works perfectly!

**Comment by hawaiianchimp** [comment]
It's fixed!
