### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by rje6459** [hawaiianchimp/kbb-craigslist#28]
Extension hasn't been working for quite some time now. Chrome console was giving the error in the title. Screenshot is what I'm seeing when I try to manually get the car page.
![capture](https://cloud.githubusercontent.com/assets/16375649/13693874/cb933d36-e71d-11e5-99cf-6e991abaf57e.PNG)

**Comment by hawaiianchimp** [comment]
It's fixed!
