### ISSUE TITLE
Chrome Addon Out of Date

### ISSUE THREAD

**Issue by kevankas** [hawaiianchimp/kbb-craigslist#29]
Hello Sean do you have any interest in updating and maintaining your Craigslist car addon so that it will be functional again? I just stumbled upon it and I don't think it's been updated since 2015. 

Thanks in advance. I would love you use your tool even if it was for $.

**Comment by hawaiianchimp** [comment]
Hmm, you know I should try to get this up and running again. Would be a fun side project to bring back to life. I'm currently strapped for time, so don't have much time to work on it. Pull requests always welcome!

**Comment by hawaiianchimp** [comment]
It's fixed!
