### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by rondellrandall** [hawaiianchimp/kbb-craigslist#30]
Hello, Man this is an incredible tool and I need it. Would you mind fixing it? PLEASE tell me thats in your in the process of doing so. lol.

**Comment by rondellrandall** [comment]
Can anyone fix this? Im willing to pay asap!

**Comment by rondellrandall** [comment]
Thats fine. Absolutely fine with that. Thank u so much. Do u know when
about?

**Comment by hawaiianchimp** [comment]
Alright I added a link so that you can still access kbb even though the API is broken.

**Comment by rondellrandall** [comment]
Ok great. Now I know this is a total newbie question. But how do I add this
to my browser from here? Bcuz this isnt the same as the extension in the
chrome store where I can add with a click

**Comment by rondellrandall** [comment]
I have googled for about an hour and cant figure out how to use github app.
Will u be updating it in the chrome store? Otherwise how will I be able to
actually use it?

**Comment by hawaiianchimp** [comment]
Hey yeah it should be updated on the chrome store. Version 1.1.7 I believe
